#ifndef TIMER_MANAGER_H
#define TIMER_MANAGER_H

#include <stdint.h>

extern unsigned long currentMillis;
extern unsigned long currentMillis_paogan;
extern unsigned long currentMillis_guaer;
extern unsigned long currentMillis_guaer5;
extern unsigned long currentMillis_guaer10;
extern unsigned long currentMillis_guaer15;
extern unsigned long currentMillis_PG;
extern unsigned long currentMillis_GR;
extern unsigned long currentMillis_GR_A;
extern unsigned long currentMillis_laji;
extern unsigned long currentMillis_bangke;

extern bool PG;
extern bool GR;
extern bool GR_A;
extern bool GR_B;
extern bool GR_C;
extern bool GR_D;
extern bool GR_E;
extern bool YPJC;
extern bool JR_ZD;
extern bool XL_90;
extern bool XL_60;
extern bool XL_50;
extern bool XL_20;
extern int QH_1;
extern int QH_2;
extern bool QH_3;
extern bool LL_90;
extern bool LL_60;
extern bool LL_50;
extern bool LL_20;
extern bool JH_JH;
extern bool XS;
extern bool LS;
extern bool XL;
extern bool LL;
extern bool DYHC;
extern bool paogan;
extern bool paogan_A;
extern bool AJ_A;
extern bool DY_A;
extern bool DY_B;
extern bool DY_C;
extern bool DY_D;
extern bool DY_E;
extern bool DY_F;
extern bool YM;
extern bool DG_A;
extern bool DG_B;
extern bool DG_C;
extern bool DG_D;
extern bool DG_E;
extern bool DG_F;
extern bool DG_G;
extern bool DG_H;
extern bool DG_I;
extern bool DG_J;
extern bool DG_K;
extern bool DG_Le;
extern bool DG_M;
extern bool YM_A;
extern bool AJSF_A;
extern bool AJSF_B;
extern bool DY_AX;
extern bool DD_AX;
extern bool BF_AX;
extern bool GH_AX;
extern bool FX_AX;
extern bool enabled;
extern bool enabled_A;
extern bool DD_A1;
extern bool DD_A2;
extern bool DD_A3;
extern bool DD_A4;
extern bool DD_A5;
extern bool BF_A1;
extern bool BF_A2;
extern bool BF_A3;
extern bool BF_A4;
extern bool BF_A5;
extern bool GH_A1;
extern bool GH_A2;
extern bool GH_A3;
extern bool S_A1;
extern bool X_A1;
extern bool Y_A1;
extern bool Z_A1;
extern bool GR_F;
extern bool QH;
extern bool DYS_A1;
extern bool DDS_A1;
extern bool YDYD;

extern char combinedText_djs[64];

extern unsigned long previousMillis_XL;
extern unsigned long previousMillis_LL;
extern const long interval_XL;
extern const long interval_LL;

extern unsigned long variableValue_AX_B;
extern unsigned long variableValue_AX_A;
extern unsigned long variableValue_AJ1_A;
extern unsigned long variableValue_AJ1_B;
extern unsigned long variableValue_AJ2_A;
extern unsigned long variableValue_AJ2_B;
extern unsigned long variableValue_AJ3_A;
extern unsigned long variableValue_AJ3_B;
extern unsigned long variableValue_AJ4_A;
extern unsigned long variableValue_AJ4_B;
extern unsigned long variableValue_AJ5_A;
extern unsigned long variableValue_AJ5_B;
extern unsigned long variableValue_AJ6_A;
extern unsigned long variableValue_AJ6_B;

extern unsigned long variableValue_JN1_A;
extern unsigned long variableValue_JN1_B;
extern unsigned long variableValue_JN2_A;
extern unsigned long variableValue_JN2_B;
extern unsigned long variableValue_JN3_A;
extern unsigned long variableValue_JN3_B;
extern unsigned long variableValue_JN4_A;
extern unsigned long variableValue_JN4_B;
extern unsigned long variableValue_JN5_A;
extern unsigned long variableValue_JN5_B;
extern unsigned long variableValue_BF1_A;
extern unsigned long variableValue_BF1_B;
extern unsigned long variableValue_BF2_A;
extern unsigned long variableValue_BF2_B;
extern unsigned long variableValue_BF3_A;
extern unsigned long variableValue_BF3_B;
extern unsigned long variableValue_BF4_A;
extern unsigned long variableValue_BF4_B;
extern unsigned long variableValue_BF5_A;
extern unsigned long variableValue_BF5_B;
extern unsigned long variableValue_GH1_A;
extern unsigned long variableValue_GH1_B;
extern unsigned long variableValue_GH2_A;
extern unsigned long variableValue_GH2_B;
extern unsigned long variableValue_GH3_A;
extern unsigned long variableValue_GH3_B;
extern unsigned long variableValue_GH3_D;
extern unsigned long variableValue_HC_D;
extern unsigned long variableValue_S_A;
extern unsigned long variableValue_S_B;
extern unsigned long variableValue_X_A;
extern unsigned long variableValue_X_B;
extern unsigned long variableValue_Z_A;
extern unsigned long variableValue_Z_B;
extern unsigned long variableValue_Y_A;
extern unsigned long variableValue_Y_B;
extern unsigned long variableValue_HC_A;
extern unsigned long variableValue_HC_B;
extern unsigned long variableValue_HC_c;

extern uint8_t DY1;
extern uint8_t DY2;
extern uint8_t DY3;
extern uint8_t DY4;
extern uint8_t DY5;
extern uint8_t DY6;
extern uint8_t DYHC1;
extern uint8_t GR1;
extern uint8_t PG1;
extern uint8_t JN1;
extern uint8_t JN2;
extern uint8_t JN3;
extern uint8_t JN4;
extern uint8_t JN5;
extern uint8_t BUF1;
extern uint8_t BUF2;
extern uint8_t BUF3;
extern uint8_t BUF4;
extern uint8_t BUF5;
extern uint8_t GH1;
extern uint8_t GH2;
extern uint8_t GH3;
extern uint8_t S;
extern uint8_t X;
extern uint8_t Z;
extern uint8_t Y;
extern uint8_t HC;

extern unsigned long JZSJ;
extern unsigned long DY_Millis[6];
extern unsigned long DY_Millis_A[6];
extern unsigned long DD_Millis[5];
extern unsigned long DD_Millis_A[5];
extern unsigned long BF_Millis[5];
extern unsigned long BF_Millis_A[5];
extern unsigned long GH_Millis[3];
extern unsigned long GH_Millis_A[3];
extern unsigned long FX_Millis[4];
extern unsigned long FX_Millis_A[4];
extern unsigned long elapsedTime;
extern unsigned long elapsedTime_A;

extern const int TOTAL_ROLES;
extern int currentRole;
extern bool roleSwitchEnabled;
extern int roleSequence[6];
extern int currentSequenceIndex;
extern int lastEndRole;

extern unsigned long lastPublishTime_A;
extern const unsigned long PUBLISH_INTERVAL;

void qiehuan();
void SUJI();
void DIAOYU();
void DAGUAI();
void executeRoleSwitch();
void shuffleRoleSequence();
void startBaitAndPrepareCast();
const char* getFishingStateLabel();
unsigned long getFishingBaitRemainingMs();

#endif
