"""Add can_activate_device field to User table

Revision ID: 1e4baafe615b
Revises: c410eab54512
Create Date: 2025-05-16 16:56:35.282066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4baafe615b'
down_revision = 'c410eab54512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_activate_device', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_activate_device')

    # ### end Alembic commands ###
