"""Add return_seconds column to Device model

Revision ID: 740db924e795
Revises: e9d9103c8fda
Create Date: 2025-06-04 21:58:27.499359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740db924e795'
down_revision = 'e9d9103c8fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('return_seconds')

    # ### end Alembic commands ###
