"""添加设备激活相关字段

Revision ID: b001972a08f8
Revises: b633276d3684
Create Date: 2025-05-16 19:08:22.835294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b001972a08f8'
down_revision = 'b633276d3684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activation_account', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('activation_account')
        batch_op.drop_column('activation_time')
        batch_op.drop_column('activated')

    # ### end Alembic commands ###
