"""Add activation_permission_start to User

Revision ID: b633276d3684
Revises: 1e4baafe615b
Create Date: 2025-05-16 18:08:48.985042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b633276d3684'
down_revision = '1e4baafe615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_permission_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('activation_permission_start')

    # ### end Alembic commands ###
