"""Initial migration

Revision ID: c410eab54512
Revises: 
Create Date: 2025-05-16 16:50:39.131093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c410eab54512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activation_codes_code'), ['code'], unique=True)

    op.create_table('device_activation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_code_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activation_code_id'], ['activation_codes.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_code_id', 'device_id', name='uq_activation_code_device')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_activation_records')
    with op.batch_alter_table('activation_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activation_codes_code'))

    op.drop_table('activation_codes')
    # ### end Alembic commands ###
