"""AXC

Revision ID: d0ad908c4400
Revises: f2b211212eea
Create Date: 2025-08-01 08:16:08.663715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ad908c4400'
down_revision = 'f2b211212eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_timers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_timers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('return_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='device_timers_pkey'),
    sa.UniqueConstraint('device_id', name='device_timers_device_id_key')
    )
    # ### end Alembic commands ###
