"""Add dd_bait_key field with default value 33

Revision ID: e9d9103c8fda
Revises: b001972a08f8
Create Date: 2025-05-27 08:25:20.296459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d9103c8fda'
down_revision = 'b001972a08f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dd_bait_key', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('dd_bait_key')

    # ### end Alembic commands ###
